bandmanager/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('about/', views.about, name='about'),
    path('bands/', views.bands_index, name='bands_index'),
    path('bands/<int:band_id>/', views.bands_detail, name='detail'),
    path('bands/create/', views.BandCreate.as_view(), name='bands_create'),
    path('bands/<int:pk>/update/', views.BandUpdate.as_view(), name='bands_update'),
    path('bands/<int:pk>/delete/', views.BandDelete.as_view(), name='bands_delete'),

    path('bands/<int:band_id>/add_venue/', views.add_venue, name='add_venue'),
    path('bands/<int:band_id>/venues/', views.venues_index, name='venues_index'),
    path('bands/<int:band_id>/venues/<int:venue_id>/', views.venues_detail, name='venues_detail'),
    path('bands/<int:band_id>/venues/create/', views.venues_create, name='venues_create'),
    path('bands/<int:band_id>/venues/<int:venue_id>/update/', views.venues_update, name='venues_update'),
    path('bands/<int:band_id>/venues/<int:venue_id>/edit_venue/', views.edit_venue, name='edit_venue'),
    path('bands/<int:band_id>/venues/<int:pk>/delete/', views.VenueDelete.as_view(), name='venues_delete'),

    path('bands/<int:band_id>/add_gig/', views.add_gig, name='add_gig'),
    path('bands/<int:band_id>/gigs/', views.gigs_index, name='gigs_index'),
    path('bands/<int:band_id>/gigs/<int:gig_id>/', views.gigs_detail, name='gigs_detail'),
    path('bands/<int:band_id>/gigs/create/', views.gigs_create, name='gigs_create'),
    path('bands/<int:band_id>/gigs/<int:gig_id>/update/', views.gigs_update, name='gigs_update'),
    path('bands/<int:band_id>/gigs/<int:gig_id>/edit_gig/', views.edit_gig, name='edit_gig'),
    path('bands/<int:band_id>/gigs/<int:pk>/delete/', views.GigDelete.as_view(), name='gigs_delete'),

    path('bands/<int:band_id>/add_inventoryItem/', views.add_inventoryItem, name='add_inventoryItem'),
    path('bands/<int:band_id>/inventory/', views.inventoryItems_index, name='inventoryItems_index'),

    path('bands/<int:band_id>/inventory/create/', views.inventoryItems_create, name='inventoryItems_create'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

STATUSES = (
    ('N', 'Not Contacted'),
    ('C', 'Contacted'),
    ('F', 'Followed Up With'),
    ('B', 'Successfully Booked'),
    ('X', 'Not Going To Work')
)

INVENTORYCATEGORIES = (
    ('CL', 'Clothing'),
    ('MU', 'Music'),
    ('ME', 'Merchandise')
)

class Band(models.Model):
    name = models.CharField(max_length=150)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'band_id': self.id})

class Venue(models.Model):
    name = models.CharField('Name (Required)', max_length=150)
    state = models.CharField('State (Required)', max_length=150)
    city = models.CharField('City (Required)', max_length=150)
    email = models.CharField(max_length=150, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    note = models.CharField(max_length=150, blank=True)
    status = models.CharField(max_length=30, choices=STATUSES, default=STATUSES[0][0])
    band = models.ForeignKey(Band, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_status_display()} on {self.name}"

    class Meta:
        ordering = ['-status']

class Gig(models.Model):
    name = models.CharField('Name (Required)', max_length=150)
    date = models.DateField('Date (Required)') # ** USE https://simpleisbetterthancomplex.com/tutorial/2019/01/03/how-to-use-date-picker-with-django.html **
    state = models.CharField('State (Required)', max_length=50)
    city = models.CharField('City (Required)', max_length=50)
    address = models.CharField(max_length=150, blank=True)
    setTime = models.CharField('Set Time', max_length=50, blank=True) # The time your band will be performing
    foh = models.CharField('Sound Person', max_length=150, blank=True) # Front of house/sound person
    fohConfirmed = models.CharField('Is the sound person confirmed?', max_length=50, blank=True) # Is the sound person confirmed?
    note = models.CharField(max_length=150, blank=True)
    band = models.ForeignKey(Band, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'band_id': self.id})

class InventoryItem(models.Model):
    # HAVE BUY AND SELL FUNCTIONALITY
    # HAVE SORT FUNCTIONALITY
    
    # item name, item category ?, quantity remaining, size, # bought, cost, # sold, selling price, date bought, date sold (for each instance), batch #?
    # SHIRT - t-shirt, clothing,              30,       M,  50 bought, $12 each, 20,   $15 each,    6/1/22,         6/5/22, 6/6/22, etc.         1? 
    # CD - IzMyHed CD,  music,            15,      jacket,  50 bought, $7 each, 35,    $10 each,    6/20/22,       6/21/22, 7/4/22, etc.         3?         
    # STICKER - sticker,  merch,         15
    
    category = models.CharField(max_length=12, choices=INVENTORYCATEGORIES, default=INVENTORYCATEGORIES[0][0])
    name = models.CharField('Name (Required)', max_length=150)
    size = models.CharField(max_length=50, blank=True)
    currentQuantity = models.PositiveIntegerField(default=0)
    batchCost = models.DecimalField(decimal_places=2, max_digits=20, blank=True)
    sellingPrice = models.DecimalField(decimal_places=2, max_digits=20, blank=True)
    dateBought = models.DateField(blank=True, default=date.today)
    dateSold = models.DateField(blank=True, default=date.today)
    band = models.ForeignKey(Band, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'band_id': self.id})

main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class DatePickerInput(forms.DateInput):
    input_type = 'date'

class VenueForm(ModelForm):
    class Meta:
        model = Venue
        fields = ['name', 'state', 'city', 'email', 'phone', 'note', 'status']

class GigForm(ModelForm):
    class Meta:
        model = Gig
        fields = ['name', 'date', 'state', 'city', 'address', 'setTime', 'foh', 'fohConfirmed', 'note']

        widgets = {
            'date' : DatePickerInput()
        }

class InventoryItemForm(ModelForm):
    class Meta:
        model = InventoryItem
        fields = ['category', 'name', 'size']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .forms import *

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

# Define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

#
# INDEX VIEWS
#

@login_required
def bands_index(request):
    bands = Band.objects.filter(user=request.user)
    return render(request, 'bands/index.html', { 'bands': bands })

@login_required
def venues_index(request, band_id):
  band = Band.objects.get(id=band_id)
  venues = band.venue_set.all()
  # venue_form = VenueForm()
  return render(request, 'venues/index.html', {
    'venues': venues,
    'band': band,
    # 'venue_form': venue_form
  })

@login_required
def gigs_index(request, band_id):
  band = Band.objects.get(id=band_id)
  gigs = band.gig_set.all()
  return render(request, 'gigs/index.html', {
    'gigs': gigs,
    'band': band,
  })

@login_required
def inventoryItems_index(request, band_id):
  band = Band.objects.get(id=band_id)
  inventoryItems = band.gig_set.all()
  return render(request, 'inventoryItems/index.html', {
    'inventoryItems': inventoryItems,
    'band': band,
  })

#
# DETAIL VIEWS
#

@login_required
def bands_detail(request, band_id):
  band = Band.objects.get(id=band_id)
  return render(request, 'bands/detail.html', { 
    'band': band,
  })

@login_required
def venues_detail(request, band_id, venue_id):
  band = Band.objects.get(id=band_id)
  venue = Venue.objects.get(id=venue_id)
  return render(request, 'venues/detail.html', { 
    'band': band,
    'venue': venue 
  })

@login_required
def gigs_detail(request, band_id, gig_id):
  band = Band.objects.get(id=band_id)
  gig = Gig.objects.get(id=gig_id)
  return render(request, 'gigs/detail.html', { 
    'band': band,
    'gig': gig
  })

#
# CREATE VIEWS
#

# GET route that takes the user to the page with the add venue form
@login_required
def venues_create(request, band_id):
  band = Band.objects.get(id=band_id)
  venue_form = VenueForm()
  return render(request, 'venues/create.html', {
    'band': band,
    'venue_form': venue_form
  })

# GET route that takes the user to the page with the add gig form
@login_required
def gigs_create(request, band_id):
  band = Band.objects.get(id=band_id)
  gig_form = GigForm()
  return render(request, 'gigs/create.html', {
    'band': band,
    'gig_form': gig_form
  })

# GET route that takes the user to the page with the add inventoryItem form
@login_required
def inventoryItems_create(request, band_id):
  band = Band.objects.get(id=band_id)
  inventoryItem_form = InventoryItemForm()
  return render(request, 'inventoryItems/create.html', {
    'band': band,
    'inventoryItem_form': inventoryItem_form
  })

#
# ADD VIEWS
#

# POST route that creates a Venue using the completed form data
@login_required
def add_venue(request, band_id):
  # create a ModelForm instance using the data in request.POST
  form = VenueForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the band_id assigned
    new_venue = form.save(commit=False)
    new_venue.band_id = band_id
    new_venue.save()
  return redirect('venues_index', band_id=band_id)

# POST route that creates a Gig using the completed form data
@login_required
def add_gig(request, band_id):
  # create a ModelForm instance using the data in request.POST
  form = GigForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the band_id assigned
    new_gig = form.save(commit=False)
    new_gig.band_id = band_id
    new_gig.save()
  return redirect('gigs_index', band_id=band_id)

# POST route that creates an InventoryItem using the completed form data
@login_required
def add_inventoryItem(request, band_id):
  # create a ModelForm instance using the data in request.POST
  form = InventoryItemForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the band_id assigned
    print('valid!')
    new_inventoryItem = form.save(commit=False)
    new_inventoryItem.band_id = band_id
    new_inventoryItem.save()
    print(new_inventoryItem)
  return redirect('inventory', band_id=band_id)

#
# UPDATE VIEWS
#

# GET route that takes the user to the page with the edit venue form
@login_required
def venues_update(request, band_id, venue_id):
  band = Band.objects.get(id=band_id)
  venue = Venue.objects.get(id=venue_id)
  return render(request, 'venues/update.html', {
    'band': band,
    'venue': venue
  })

# GET route that takes the user to the page with the edit gig form
@login_required
def gigs_update(request, band_id, gig_id):
  band = Band.objects.get(id=band_id)
  gig = Gig.objects.get(id=gig_id)
  return render(request, 'gigs/update.html', {
    'band': band,
    'gig': gig
  })

#
# EDIT VIEWS
#

# POST route that edits the current Venue using the completed form data
@login_required
def edit_venue(request, band_id, venue_id):
  # venue = Venue.objects.get(id=venue_id)
  form = VenueForm(request.POST)
  # validate the form
  if form.is_valid():
    venue = form.save(commit=False)
    band = Band.objects.get(id=band_id)
    venue.id = venue_id
    venue.band_id = band.id
    venue.save()
  return redirect('venues_index', band_id=band_id)

# POST route that edits the current Gig using the completed form data
@login_required
def edit_gig(request, band_id, gig_id):
  form = GigForm(request.POST)
  if form.is_valid():
    gig = form.save(commit=False)
    band = Band.objects.get(id=band_id)
    gig.id = gig_id
    gig.band_id = band.id
    gig.save()
  return redirect('gigs_index', band_id=band_id)

#
# GENERIC VIEWS
#

class BandCreate(LoginRequiredMixin, CreateView):
  model = Band
  fields = ['name']
  success_url = '/bands/'

  # This inherited method is called when a
  # valid band form is being submitted
  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the band
    # Let the CreateView do its job as usual
    return super().form_valid(form)

# **NEED TO REMOVE ABILITY TO UPDATE AND DELETE BANDS LATER**
class BandUpdate(LoginRequiredMixin, UpdateView):
  model = Band
  fields = []

class BandDelete(LoginRequiredMixin, DeleteView):
  model = Band
  success_url = '/bands/'
# **NEED TO REMOVE ABILITY TO UPDATE AND DELETE BANDS LATER**

class VenueDelete(LoginRequiredMixin, DeleteView):
  model = Venue
  success_url = '/bands/'

class GigDelete(LoginRequiredMixin, DeleteView):
  model = Gig
  success_url = '/bands/'

main_app/templates/gigs/create.html
{% extends 'base.html' %}
{% block content %}

{% if band.user.username == user.username %}
<!-- <div class="center-align"> -->
    <h3>Add A Gig</h3>

    <form action="{% url 'add_gig' band.id %}" method="POST">
        {% csrf_token %}
        {{ gig_form.as_p }}
        <input type="submit" class="btn" value="Add Gig">
    </form>
<!-- </div> -->

{% endif %}

{% endblock %}

main_app/templates/gigs/detail.html
{% extends 'base.html' %}
{% block content %}

{% if band.user.username == user.username %}
<h1>{{ gig.name }}</h1>

<div class="row">
    <div class="card">
        <div class="card-content">
            <h3>Date: {{ gig.date }}</h3>
            <h3>State: {{ gig.state }}</h3>
            <h3>City: {{ gig.city }}</h3>
            <h3>Address: {{ gig.address }}</h3>
            <h3>Set Time: {{ gig.setTime }}</h3>
            <h3>Sound Person: {{ gig.foh }}</h3>
            <h3>Is the sound person confirmed?: {{ gig.fohConfirmed }}</h3>
            <h3>Note: {{ gig.note }}</h3>
        </div>
        <div class="card-action">
            <a href="{% url 'gigs_update' band.id gig.id %}">Edit</a>
            <a href="{% url 'gigs_delete' band.id gig.id %}">Delete</a>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

main_app/templates/gigs/index.html
{% extends 'base.html' %}
{% block content %}

{% if band.user.username == user.username %}
<div class="center-align">
    <h2>Gigs</h2>

    <div class="row">
        <a href="{% url 'gigs_create' band.id %}">
            <input type="button" class="btn" value="Add Gig">
            </form><br><br>

            {% for gig in band.gig_set.all %}
            <div class="card grey lighten-3">
                <a href="{% url 'gigs_detail' band.id gig.id %}">
                    <span class="card-title">{{gig.name}}</span>
                    <div class="card-content">
                        <p>{{gig.date}}</p>
                        <p>{{gig.city}}, {{gig.state}}</p>
                    </div>
            </div>
            {% endfor %}
    </div>
</div>

{% endif %}

{% endblock %}

main_app/templates/gigs/update.html
{% extends 'base.html' %}
{% block content %}

{% if band.user.username == user.username %}
<h1>Edit <span class="teal-text">{{gig.name}}</span></h1>

<form action="{% url 'edit_gig' band.id gig.id %}" method="POST">
    {% csrf_token %}
    <p><label for="id_name">Name (Required):</label>
        <input id="id_name" type="text" value="{{ gig.name }}" name="name">
    </p>
    <p><label for="id_date">Date (Required):</label>
        <input id="id_date" type="text" name="date" onclick="changeDate()">
    </p>
    <p><label for="id_state">State (Required):</label>
        <input id="id_state" type="text" value="{{ gig.state }}" name="state">
    </p>
    <p><label for="id_city">City (Required):</label>
        <input id="id_city" type="text" value="{{ gig.city }}" name="city">
    </p>
    <p><label for="id_address">Address:</label>
        <input id="id_address" type="text" value="{{ gig.address }}" name="address">
    </p>
    <p><label for="id_setTime">Set Time:</label>
        <input id="id_setTime" type="text" value="{{ gig.setTime }}" name="setTime">
    </p>
    <p><label for="id_foh">Sound Person:</label>
        <input id="id_foh" type="text" value="{{ gig.foh }}" name="foh">
    </p>
    <p><label for="id_fohConfirmed">Is the sound person confirmed?</label>
        <input id="id_fohConfirmed" type="text" value="{{ gig.fohConfirmed }}" name="fohConfirmed">
    </p>
    <p><label for="id_note">Note:</label>
        <input id="id_note" type="text" value="{{ gig.note }}" name="note">
    </p>
    <input type="submit" class="btn" value="Submit Changes">
</form>
{% endif %}

<script>
    function changeDate() {
        document.getElementById("id_date").type = "date"
    }

    const date = `{{ gig.date }}`
    const newDate = new Date(date)
    const localeDate = newDate.toLocaleDateString()
    document.getElementById("id_date").value = localeDate
</script>

{% endblock %}

<!-- 

-->